In [4]:
import pandas as pd

In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# define the scope
scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/drive.file','https://www.googleapis.com/auth/drive']

# add credentials to the account
creds = ServiceAccountCredentials.from_json_keyfile_name('testsheet.json', scope)

# authorize the clientsheet
client = gspread.authorize(creds)

# get the instance sheet of the Spreadsheet
sheet = client.open("Bot Spreadsheet").sheet1

# get all the records of the data
data = sheet.get_all_records()

In [2]:
len(data)

25

In [5]:
# convert the json to dataframe
records_df = pd.DataFrame.from_dict(data)

# view the top records
records_df.head()

,Save time,id,Patient Name,Age/Sex,Room Number,Primary Physician,Comorbidities,Day of stay,Day of ICU stay,GCS,...,D Dimer,LDH,CxR,APACHE IV,HAS BLED,GFR,SOFA score,Other Scores,INSTRUCTIONS,Discharged
0,,0,A,40/M,ICU-313,DR. SKS,"DM, HTN, CLD",4,4,15/15,...,4000,2,Normal,100,alright,114,5,,Continue the same treatment,NO
1,,1,B,78/F,232,DR pop,CAD,,,,...,,,,,,,,,,NO
2,,2,C,90/F,ICU-313,DR. AKUL,"DM, HTN",3,1,,...,,,,,,,,,,NO
3,,3,D,80/M,ICU-318,Dr. SK,"CKD, CLD",4,3,E1VTM2,...,234,2342,234,,high,25,15,,DNR,NO
4,,4,E,40/M,P4-23,DR. AKS,DM,3,-,15/15,...,,,,K,L,M,W,X,CST,NO

In [6]:
df_data = records_df

In [7]:
Patient_Id = 3
df_data_patient_id = df_data[df_data['id'] == int(Patient_Id)]
df_data_last_row = df_data_patient_id.iloc[[-1]]

In [8]:
df_data_last_row

,Save time,id,Patient Name,Age/Sex,Room Number,Primary Physician,Comorbidities,Day of stay,Day of ICU stay,GCS,...,D Dimer,LDH,CxR,APACHE IV,HAS BLED,GFR,SOFA score,Other Scores,INSTRUCTIONS,Discharged
20,24/10/2020 22:39:58,3,D,80/M,ICU-318,Dr. SK,"CKD, CLD",4,3,E1VTM2,...,234,2342,234,,high,25,15,,Good,NO

In [10]:
df_data_last_row = df_data_patient_id.iloc[[-1]]
#context.user_data['patient_id_row'] = df_data_last_row
text = ''
for column in df_data_last_row.columns.values[:-1]:
    text = text + '\n' + column + ': ' + str(df_data_last_row[column].values[0])

Save time: 24/10/2020 22:39:58
id: 3
Patient Name: D
Age/Sex: 80/M
Room Number: ICU-318
Primary Physician: Dr. SK
Comorbidities: CKD, CLD
Day of stay: 4
Day of ICU stay: 3
GCS: E1VTM2
Ventilation: VCV FiO2 .5 Vt 300 m
SPO2: 80%
PR: 50
BP: 75/60
INOTROPE: Inf Nor-adr @ 5 ml/hr
ANALGESIA: -
SEDATION: -
ANTIBIOTIC(S): Inj Tazact 2.25 mg TDS D1


Inj qqqqq
Other drugs: Inj EPO 5000 Units
INSULIN infusion: -
ULCER PROPHYLAXIS: -
REMDESIVIR: x
Anticoagulation: x
METHYLPREDNISOLONE EQUI DOSE DEXA (1.5:8): âœ“
TOCILIZUMAB: Completed
STOOL: -
FEVER: febrile
FEED: Not accepting
I/O: 1000 ml+
RTA/DRAIN: 100 ml/-
Hemogram: Hb 5/TLC increasing
Coagulogram: WNL
SE: WNL
RFT: WNL
ABG/VBG: WNL
RBS: WNL
Special Ix: WNL
Date: 29>>>2nd october
IL 6: 234234
Ferritin: 234234
CRP: 234234
D Dimer: 234
LDH: 2342
CxR: 234
APACHE IV:
HAS BLED: high
GFR: 25
SOFA score: 15
Other Scores:
INSTRUCTIONS: Good

In [15]:
df_data_last_row

,Save time,id,Patient Name,Age/Sex,Room Number,Primary Physician,Comorbidities,Day of stay,Day of ICU stay,GCS,...,D Dimer,LDH,CxR,APACHE IV,HAS BLED,GFR,SOFA score,Other Scores,INSTRUCTIONS,Discharged
20,24/10/2020 22:39:58,3,D,80/M,ICU-318,Dr. SK,"CKD, CLD",4,3,E1VTM2,...,234,2342,234,,high,25,15,,Good,NO

In [14]:
df_data_last_row.iloc[-1]['Discharged']

'NO'

In [13]:
df_data_last_row.index[-1]

20